name: Priviblur CI

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00
  push:
    branches:
      - "master"
  pull_request:
    branches: "*"
    paths-ignore:
      - "*.md"
      - screenshots/*
      - utils/**
      - assets/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and test on ${{matrix.python-version}}"
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r utils/i18n/requirements.txt

    - name: Generate locale data
      run: python ./utils/i18n/generate.py

    - name: Setup config
      run: cp config.example.toml config.toml

    - name: Compile locales
      run: pybabel compile -d locales -D priviblur
      
    - name: Run 
      run : |
        python -m src.server &

    - name: Wait and test
      run: sleep 5 && curl -Isf http://localhost:8000/explore/trending